# Generated by Django 2.2.17 on 2020-12-09 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmAdvertisingTopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Maximum de 75 caractères.', max_length=75, verbose_name='Texte')),
                ('link', models.CharField(blank=True, help_text='Exemple: https://www.test.com. Laissez vide pour ne pas utiliser de lien.', max_length=1000, null=True, verbose_name='Lien URL')),
                ('open_blank', models.BooleanField(default=False, verbose_name='Ouvrir le lien dans un nouvel onglet ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date de début')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': "Banderole d'entête publicitaire",
                'verbose_name_plural': "Banderoles d'entête publicitaires",
            },
        ),
    ]
