# Generated by Django 2.2.17 on 2021-01-04 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdvertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmadvertisingtopbanner',
            options={'verbose_name': 'Advertising Top Banner', 'verbose_name_plural': 'Advertising Top Banners'},
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='link',
            field=models.CharField(blank=True, help_text='Example: https://www.test.com. Leave blank to not use link.', max_length=1000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='open_blank',
            field=models.BooleanField(default=False, verbose_name='Open on a new tab?'),
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='text',
            field=models.CharField(help_text='Maximum 75 characters.', max_length=75, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start at'),
        ),
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End at'),
        ),
    ]
