# Generated by Django 2.2.18 on 2021-02-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dmAdvertising', '0002_auto_20210104_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmadvertisingtopbanner',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at'),
        ),
        migrations.CreateModel(
            name='dmAdvertisingPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 75 characters.', max_length=75, verbose_name='title')),
                ('link', models.CharField(blank=True, help_text='Facultative.', max_length=1000, null=True, verbose_name='URL Link')),
                ('close_30days', models.BooleanField(default=True, help_text='Hide popup for 30 days on close, otherwise, show it everytime on each page.', verbose_name='Hide for 30 days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='End at')),
                ('shown', models.PositiveSmallIntegerField(default=0, verbose_name='Shown')),
                ('image', filer.fields.image.FilerImageField(help_text='Recommended size: 800x600.', on_delete=django.db.models.deletion.CASCADE, related_name='advertisingpopup_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Advertising Popup',
                'verbose_name_plural': 'Advertising Popups',
                'ordering': ['is_active', '-id'],
            },
        ),
    ]
