# Generated by Django 2.2.18 on 2021-05-31 17:24

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdvertising', '0004_auto_20210303_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmadvertisingtopbanner',
            name='text',
        ),
        migrations.CreateModel(
            name='dmAdvertisingTopBannerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(help_text='Maximum 75 characters.', max_length=75, verbose_name='Text')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dmAdvertising.dmAdvertisingTopBanner')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
