# Generated by Django 2.2.18 on 2021-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdvertising', '0005_auto_20210531_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmadvertisingtopbanner',
            name='link',
        ),
        migrations.AddField(
            model_name='dmadvertisingtopbannertranslation',
            name='link',
            field=models.CharField(blank=True, help_text='Example: https://www.test.com. Leave blank to not use link.', max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
