# Generated by Django 2.2.18 on 2021-05-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdvertising', '0006_auto_20210531_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmadvertisingpopup',
            old_name='image',
            new_name='image_fr',
        ),
    ]
