# Generated by Django 2.2.18 on 2021-08-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dmAdvertising', '0008_auto_20210531_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmadvertisingpopup',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='dmadvertisingpopup',
            name='image_fr',
        ),
        migrations.RemoveField(
            model_name='dmadvertisingpopup',
            name='link',
        ),
        migrations.CreateModel(
            name='dmAdvertisingPopupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('link', models.CharField(blank=True, help_text='Optional.', max_length=1000, null=True, verbose_name='URL Link')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Recommended size: 800x600.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisingpopup_image_en', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dmAdvertising.dmAdvertisingPopup')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
