# Generated by Django 2.2.18 on 2021-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdvertising', '0009_auto_20210826_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmadvertisingpopup',
            name='title',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Title'),
        ),
    ]
