# Generated by Django 2.2.17 on 2020-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmRabais', '0001_initial'),
        ('dshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmrabaispercategory',
            name='categories',
            field=models.ManyToManyField(related_name='rabaispercategory', to='dshop.ProductCategory', verbose_name='Categories'),
        ),
    ]
