# Generated by Django 2.2.17 on 2020-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0001_initial'),
        ('dmRabais', '0003_auto_20201215_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Un montant fixe à retirer du prix original, laisser vide pour privilégier le pourcentage.', max_digits=30, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='dmpromocode',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Un pourcentage à retirer du prix original, ne sera pas utilisé s'il y a un montant dans 'Montant fixe'.", null=True, verbose_name='Percent'),
        ),
        migrations.AddField(
            model_name='dmpromocode',
            name='products',
            field=models.ManyToManyField(help_text='Leave blank if you want to apply to all product.', related_name='promocode', to='dshop.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='dmpromocode',
            name='code',
            field=models.CharField(help_text='Leave blank to auto-generate a random code.', max_length=120, verbose_name='Code'),
        ),
    ]
