# Generated by Django 2.2.17 on 2020-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0004_auto_20201215_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate a random code.', max_length=120, verbose_name='Code'),
        ),
    ]
