# Generated by Django 2.2.17 on 2020-12-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0005_auto_20201215_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if you want to apply to all product.', related_name='promocode', to='dshop.ProductCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='dmpromocode',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if you want to apply to all product.', related_name='promocode', to='dshop.Product', verbose_name='Products'),
        ),
    ]
