# Generated by Django 2.2.17 on 2020-12-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0002_auto_20201215_1533'),
        ('dmRabais', '0006_auto_20201215_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmCustomerPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshop.Customer', verbose_name='Customer')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmRabais.dmPromoCode', verbose_name='Promo Code')),
            ],
            options={
                'verbose_name': "Customer's Promo Code",
                'verbose_name_plural': "Customer's Promo Codes",
            },
        ),
    ]
