# Generated by Django 2.2.17 on 2021-01-04 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0007_dmcustomerpromocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmrabaispercategory',
            options={'verbose_name': 'Discount Per Category', 'verbose_name_plural': 'Discounts Per Category'},
        ),
        migrations.AlterField(
            model_name='dmpromocode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="An amount to substract to the original price, leave blank to use 'Percent'.", max_digits=30, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='dmpromocode',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="A percent to substract to the original price, unused if there's an 'Amount'.", null=True, verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="An amount to substract to the original price, leave blank to use 'Percent'.", max_digits=30, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="A percent to substract to the original price, unused if there's an 'Amount'.", null=True, verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start at'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End at'),
        ),
    ]
