# Generated by Django 2.2.17 on 2021-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0008_auto_20210104_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='name',
            field=models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='name',
            field=models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Name'),
        ),
    ]
