# Generated by Django 2.2.17 on 2021-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0009_auto_20210104_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='can_apply_on_discounted',
            field=models.BooleanField(default=False, verbose_name='Can Apply On Discounted Product?'),
        ),
        migrations.AddField(
            model_name='dmrabaispercategory',
            name='can_apply_on_discounted',
            field=models.BooleanField(default=False, verbose_name='Can Apply On Discounted Product?'),
        ),
    ]
