# Generated by Django 2.2.17 on 2021-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0010_auto_20210107_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='apply_on_cart',
            field=models.BooleanField(default=False, help_text="Check to apply this promocode on the cart's total instead of individual product.", verbose_name="Apply on cart's total only"),
        ),
    ]
