# Generated by Django 2.2.18 on 2021-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0011_dmpromocode_apply_on_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Amount Discount'), (2, 'Percent Discount')], default=1, verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='dmrabaispercategory',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Amount Discount'), (2, 'Percent Discount')], default=1, verbose_name='Discount Type'),
        ),
    ]
