# Generated by Django 2.2.17 on 2021-02-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0011_dmpromocode_apply_on_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmpromocode',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='dmrabaispercategory',
            name='discount_type',
        ),
    ]
