# Generated by Django 2.2.17 on 2021-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0011_dmpromocode_apply_on_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="A percent to substract to the original price, unused if there's an 'Amount'.", null=True, verbose_name='Percent'),
        ),
        migrations.AddField(
            model_name='dmrabaispercategory',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="A percent to substract to the original price, unused if there's an 'Amount'.", null=True, verbose_name='Percent'),
        ),
    ]
