# Generated by Django 2.2.17 on 2021-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0012_auto_20210208_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmpromocode',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='dmrabaispercategory',
            name='percent',
        ),
    ]
