# Generated by Django 2.2.18 on 2021-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0012_dmpromocode_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='customer',
            field=models.ManyToManyField(limit_choices_to={'get_recognized_display': 'Registered'}, related_name='customerpromo', to='dshop.Customer', verbose_name='Customers'),
        ),
    ]
