# Generated by Django 2.2.18 on 2021-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0013_auto_20210318_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='customer',
            field=models.ManyToManyField(blank=True, limit_choices_to={'recognized': 2}, null=True, related_name='customerpromo', to='dshop.Customer', verbose_name='Customers'),
        ),
    ]
