# Generated by Django 2.2.18 on 2021-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0015_auto_20210322_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmpromocode',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='Autoriser plusieurs utilisateurs'),
        ),
    ]
