# Generated by Django 2.2.18 on 2021-04-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0017_auto_20210323_1418'),
        ('dmRabais', '0012_auto_20210219_1418'),
    ]

    operations = [
    ]
