# Generated by Django 2.2.18 on 2021-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0018_merge_20210401_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmpromocode',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='dmrabaispercategory',
            name='discount_type',
        ),
    ]
