# Generated by Django 2.2.18 on 2021-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmRabais', '0019_auto_20210406_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmpromocode',
            name='code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate a random code.', max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='dmpromocode',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dmrabaispercategory',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Name'),
        ),
    ]
