# Generated by Django 2.2.17 on 2021-02-09 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.money.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Quotation Code')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'CREATED'), (2, 'APPROVED'), (3, 'ORDERED'), (4, 'REJECTED')], default=1, verbose_name='Quotation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quotation Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Quotation Updated at')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
            },
        ),
        migrations.CreateModel(
            name='dmQuotationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name="Product's Name")),
                ('product_code', models.CharField(blank=True, max_length=255, null=True, verbose_name="Product's Code")),
                ('variant_code', models.CharField(blank=True, max_length=255, null=True, verbose_name="Variant's Code")),
                ('unit_price', shop.money.fields.MoneyField(blank=True, decimal_places=3, null=True, verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='dmQuotation.dmQuotation')),
            ],
        ),
    ]
