# Generated by Django 2.2.17 on 2021-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmQuotation', '0002_auto_20210210_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmquotation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREATED'), (2, 'SUBMITTED'), (3, 'APPROVED'), (4, 'ORDERED'), (5, 'REJECTED')], default=1, verbose_name='Quotation Status'),
        ),
    ]
