# Generated by Django 2.2.17 on 2021-02-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmQuotation', '0003_auto_20210210_1136'),
        ('dmQuotation', '0005_dmquotationitem_variant_attribute'),
    ]

    operations = [
    ]
