# Generated by Django 2.2.18 on 2021-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmQuotation', '0008_auto_20210212_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmquotation',
            name='cookie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie ID'),
        ),
        migrations.AlterField(
            model_name='dmquotationitem',
            name='variant_attribute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Variant Attribute'),
        ),
    ]
