language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install flake8

before_script: pip install docker-compose

script:
  - docker-compose -f docker-compose-test.yml up db &
  - sleep 5
  - docker-compose -f docker-compose-test.yml run --rm web python manage.py migrate
  - docker-compose -f docker-compose-test.yml run --rm web  bash -c "python manage.py collectstatic && python manage.py test" && flake8 --exclude migrations
