language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose -f docker-compose-test.yml up db
  - sleep 5
  - docker-compose -f docker-compose-test.yml run --rm web python manage.py test && flake8
