# Generated by Django 2.2.17 on 2020-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmanagement',
            options={'ordering': ['name', '-pk'], 'verbose_name': 'Shipping Method', 'verbose_name_plural': 'Shipping Methods'},
        ),
        migrations.AddField(
            model_name='shippingmanagement',
            name='price_after',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The price to replace the original shipping price if the separator's amount has been reached.", max_digits=10, null=True, verbose_name='After price'),
        ),
        migrations.AddField(
            model_name='shippingmanagement',
            name='separator',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The amount of the cart price to separate the shipping price before and after it.', max_digits=10, null=True, verbose_name='Separator'),
        ),
        migrations.AddField(
            model_name='shippingmanagement',
            name='use_separator',
            field=models.BooleanField(default=True, verbose_name='Use an amount to separate two price?'),
        ),
        migrations.AlterField(
            model_name='shippingmanagement',
            name='identifier',
            field=models.CharField(choices=[('free-shipping', 'Postal shipping (free)'), ('standard-shipping', 'Postal shipping (standard)'), ('express-shipping', 'Postal shipping (express)'), ('standard-separator-shipping', 'Postal shipping with separator (standard)'), ('express-separator-shipping', 'Postal shipping with separator (express)')], default='free-shipping', max_length=100, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='shippingmanagement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingmanagement',
            name='price',
            field=models.DecimalField(decimal_places=3, help_text='An amount to be added to the cart price.', max_digits=30, verbose_name='Price'),
        ),
    ]
