# Generated by Django 2.2.17 on 2021-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0002_auto_20201215_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanagement',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Name'),
        ),
    ]
