# Generated by Django 2.2.17 on 2021-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0004_auto_20210112_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanagement',
            name='price_after',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The price to replace the original shipping price if the separator's amount has been reached.", max_digits=10, null=True, verbose_name='Shipping price when the amount has been reached'),
        ),
        migrations.AlterField(
            model_name='shippingmanagement',
            name='separator',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The amount of the cart price to separate the shipping price before and after it.', max_digits=10, null=True, verbose_name='Amount to reach to get the discount'),
        ),
    ]
