# Generated by Django 2.2.18 on 2021-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0005_auto_20210118_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmanagement',
            name='taxed_shipping',
            field=models.BooleanField(default=False, verbose_name='Tax shipping ?'),
        ),
    ]
