# Generated by Django 2.2.18 on 2021-02-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0006_shippingallowed_shippingcity_shippingcountry_shippingstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingallowed',
            options={'verbose_name': 'Shipping City', 'verbose_name_plural': 'Shipping Cities'},
        ),
        migrations.AlterModelOptions(
            name='shippingcountry',
            options={'ordering': ['code', '-pk'], 'verbose_name': 'Shipping Country', 'verbose_name_plural': 'Shipping Countries'},
        ),
        migrations.AlterModelOptions(
            name='shippingstate',
            options={'ordering': ['code', '-pk'], 'verbose_name': 'Shipping State', 'verbose_name_plural': 'Shipping States'},
        ),
        migrations.AlterField(
            model_name='shippingcity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='dmShipping.ShippingState', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingstate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='dmShipping.ShippingCountry', verbose_name='Country'),
        ),
    ]
