# Generated by Django 2.2.18 on 2021-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0006_shippingmanagement_taxed_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanagement',
            name='taxed_shipping',
            field=models.BooleanField(default=False, help_text="Leave unchecked if you don't want to tax shipping.", verbose_name='Tax shipping?'),
        ),
    ]
