# Generated by Django 2.2.18 on 2021-02-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0007_auto_20210219_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingallowed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingcity',
            options={'ordering': ['state', 'code'], 'verbose_name': 'Shipping City', 'verbose_name_plural': 'Shipping Cities'},
        ),
        migrations.AlterModelOptions(
            name='shippingstate',
            options={'ordering': ['country', 'code'], 'verbose_name': 'Shipping State', 'verbose_name_plural': 'Shipping States'},
        ),
    ]
