# Generated by Django 2.2.18 on 2021-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0009_auto_20210222_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingstate',
            name='name',
            field=models.CharField(help_text='Maximum 50 characters.', max_length=100, verbose_name='State Name'),
        ),
    ]
