# Generated by Django 2.2.18 on 2021-04-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0011_auto_20210223_0611'),
        ('dmShipping', '0007_auto_20210330_1056'),
    ]

    operations = [
    ]
