# Generated by Django 2.2.18 on 2021-08-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0014_auto_20210531_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmanagement',
            options={'ordering': ['-pk'], 'verbose_name': 'Shipping Method', 'verbose_name_plural': 'Shipping Methods'},
        ),
        migrations.RemoveField(
            model_name='shippingmanagement',
            name='name',
        ),
    ]
