# Generated by Django 2.2.18 on 2021-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmShipping', '0016_auto_20210825_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcity',
            name='code',
            field=models.CharField(help_text='Maximum 10 characters.', max_length=10, verbose_name='City Code'),
        ),
        migrations.AlterField(
            model_name='shippingcity',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='shippingcountry',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='shippingstate',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='State Name'),
        ),
    ]
