# Generated by Django 2.2.18 on 2021-03-15 11:24

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0002_auto_20210312_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmjobapplication',
            options={'verbose_name': "Demande d'emploi", 'verbose_name_plural': "Demandes d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='dmjobdescription',
            options={'verbose_name': "Description de l'emploi", 'verbose_name_plural': 'Description du travail'},
        ),
        migrations.AddField(
            model_name='dmjobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé à'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='document',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Votre CV'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='email',
            field=models.CharField(max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='message',
            field=models.TextField(verbose_name='Un message'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour à'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé à'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='description',
            field=models.TextField(verbose_name="Description de l'emploi"),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='joining',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Durée prévue de l'adhésion"),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='salary',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Un salaire'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='skills',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='training',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formation requise?'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour à'),
        ),
        migrations.AlterField(
            model_name='dmjobdescription',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horaire de travail'),
        ),
    ]
