# Generated by Django 2.2.18 on 2021-03-15 11:26

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0003_auto_20210315_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmjobapplication',
            name='document',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Votre CV'),
        ),
    ]
