# Generated by Django 2.2.18 on 2021-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0004_auto_20210315_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmjobdescription',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
