# Generated by Django 2.2.18 on 2021-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0005_dmjobdescription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmjobapplication',
            name='email',
            field=models.CharField(max_length=1000, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='dmjobapplication',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nom'),
        ),
    ]
