# Generated by Django 2.2.18 on 2021-03-18 13:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dmJobModule', '0006_auto_20210318_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmJobLastest',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dmjobmodule_dmjoblastest', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('btn_label', models.CharField(blank=True, help_text='Maximum 30 characters.', max_length=30, null=True, verbose_name="Link's Label")),
                ('btn_url', models.CharField(blank=True, help_text='Maximum 1 000 characters.', max_length=1000, null=True, verbose_name='URL')),
                ('btn_blank', models.BooleanField(default=False, verbose_name='Open on new tab?')),
                ('bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour")),
                ('image', models.ImageField(blank=True, help_text='Leave blank to hide image.', null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
