# Generated by Django 2.2.18 on 2021-03-18 14:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0008_auto_20210318_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmjoblastest',
            name='btn_url',
        ),
        migrations.AddField(
            model_name='dmjoblastest',
            name='box_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Box's Colour"),
        ),
        migrations.AlterField(
            model_name='dmjoblastest',
            name='btn_label',
            field=models.CharField(blank=True, default='Voir toutes les offres', help_text='Maximum 30 characters.', max_length=30, null=True, verbose_name="See All Offers Link's Label"),
        ),
    ]
