# Generated by Django 2.2.18 on 2021-03-18 14:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmJobModule', '0009_auto_20210318_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmjoblastest',
            old_name='box_color',
            new_name='box_bg_color',
        ),
        migrations.AddField(
            model_name='dmjoblastest',
            name='box_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Box Text's Colour"),
        ),
    ]
