# Generated by Django 2.2.18 on 2021-08-31 18:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name used to recognize your custom themes.', max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Only the last created active theme will be used.', verbose_name='Active')),
                ('bg_base', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site background.', max_length=18, verbose_name="Site Background's Colour")),
                ('txt_base', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site default text.', max_length=18, verbose_name="Site Text's Colour")),
                ('lnk_base', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site default link text.', max_length=18, verbose_name="Site Link's Colour")),
                ('hov_base', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site default link text on hover.', max_length=18, verbose_name="Site Hover's Colour")),
                ('rad_button', models.CharField(choices=[('2rem', 'Circle'), ('.25rem', 'Rounded'), ('0', 'Square')], default='.25rem', help_text='Applied to the site default buttons.', max_length=10, verbose_name="Button's Shape")),
                ('txt_button', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site default buttons text.', max_length=18, verbose_name="Button Text's Colour")),
                ('bor_button', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site default buttons border.', max_length=18, verbose_name="Button Border's Colour")),
                ('bg_button', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site default buttons background.', max_length=18, verbose_name="Button Background's Colour")),
                ('txt_hov_button', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site default buttons text on hover.', max_length=18, verbose_name="Button Text's Hover Colour")),
                ('bor_hov_button', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site default buttons border on hover.', max_length=18, verbose_name="Button Border's Colour")),
                ('bg_hov_button', colorfield.fields.ColorField(blank=True, default=None, help_text='Applied to the site default buttons background on hover.             Leave blank to use transparent.', max_length=18, null=True, verbose_name="Button Background's Hover Colour")),
                ('rad_input', models.CharField(choices=[('32px', 'Circle'), ('4px', 'Rounded'), ('0', 'Square')], default='4px', help_text='Applied to the site default inputs (ex:             on the contact page).', max_length=5, verbose_name="Input's Shape")),
                ('bg_input', colorfield.fields.ColorField(default='#fff', help_text='Applied to the site default inputs (ex:             on the contact page).', max_length=18, verbose_name="Input Background's Colour")),
                ('bor_input', colorfield.fields.ColorField(default='#ced4da', help_text='Applied to the site default inputs (ex:             on the contact page).', max_length=18, verbose_name="Input Border's Colour")),
                ('txt_input', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site default inputs (ex:             on the contact page).', max_length=18, verbose_name="Input Text's Colour")),
                ('rad_checkbox', models.CharField(choices=[('50%', 'Circle'), ('4px', 'Rounded'), ('0', 'Square')], default='4px', help_text='Applied to the site default checkboxes (ex:             on the products list page).', max_length=5, verbose_name="Checkbox's Shape")),
                ('bco_checkbox', colorfield.fields.ColorField(default='#ced4da', help_text='Applied to the site default checkboxes (ex:             on the products list page).', max_length=18, verbose_name="Checkbox's Colour")),
                ('act_checkbox', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site default checkboxes background when             checked (ex: on the products list page).', max_length=18, verbose_name="Checked Checkbox's Colour")),
                ('act_chk_checkbox', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site default checkboxes check when             checked (ex: on the products list page).', max_length=18, verbose_name="Checked Checkbox Check's Colour")),
                ('bg_topbar', colorfield.fields.ColorField(default='#eeeeee', help_text='Applied to the advertising banner background.', max_length=18, verbose_name="Advertising Banner Background's Colour")),
                ('txt_topbar', colorfield.fields.ColorField(default='#202325', help_text='Applied to the advertising banner text.', max_length=18, verbose_name="Advertising Banner Text's Colour")),
                ('hov_topbar', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the advertising banner text on hover.', max_length=18, verbose_name="Advertising Banner Text's Hover Colour")),
                ('bg_tophead', colorfield.fields.ColorField(default='#ffffff', help_text='Applied to the site header banner background.', max_length=18, verbose_name="Header Banner Background's Colour")),
                ('txt_tophead', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site header banner text.', max_length=18, verbose_name="Header Banner Text's Colour")),
                ('hov_tophead', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site header banner text on hover.', max_length=18, verbose_name="Header Banner Text's Hover Colour")),
                ('bg_topnav', colorfield.fields.ColorField(default='#141617', help_text='Applied to the main navigation background.', max_length=18, verbose_name="Main Navigation Background's Colour")),
                ('txt_topnav', colorfield.fields.ColorField(default='#ffffff', help_text='Applied to the main navigation text.', max_length=18, verbose_name="Main Navigation Text's Colour")),
                ('hov_topnav', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site main navigation text on hover.', max_length=18, verbose_name="Main Navigation Text's Hover Colour")),
                ('bg_topsubnav', colorfield.fields.ColorField(default='#ffffff', help_text='Applied to the main navigation sub-menu background.', max_length=18, verbose_name="Main Navigation Sub-Menu Background's Colour")),
                ('txt_topsubnav', colorfield.fields.ColorField(default='#141617', help_text='Applied to the main navigation sub-menu text.', max_length=18, verbose_name="Main Navigation Sub-Menu Text's Colour")),
                ('hov_topsubnav', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site main navigation sub-menu text             on hover.', max_length=18, verbose_name="Main Navigation Sub-Menu Text's Hover Colour")),
                ('bg_footer', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site footer background.', max_length=18, verbose_name="Footer Background's Colour")),
                ('txt_footer', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site footer text.', max_length=18, verbose_name="Footer Text's Colour")),
                ('ttl_footer', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site footer title.', max_length=18, verbose_name="Footer Title's Colour")),
                ('lnk_footer', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site footer link.', max_length=18, verbose_name="Footer Link's Colour")),
                ('lnk_hov_footer', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site footer link on hover.', max_length=18, verbose_name="Footer Link's Hover Colour")),
                ('bg_footcopy', colorfield.fields.ColorField(default='#202325', help_text='Applied to the site copyright banner background.', max_length=18, verbose_name="Copyright Background's Colour")),
                ('sep_footcopy', colorfield.fields.ColorField(default='#37393b', help_text='Applied to the site copyright banner separator.', max_length=18, verbose_name="Copyright Separator's Colour")),
                ('txt_footcopy', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site copyright banner text.', max_length=18, verbose_name="Copyright Text's Colour")),
                ('lnk_footcopy', colorfield.fields.ColorField(default='#fbfbfb', help_text='Applied to the site copyright banner link.', max_length=18, verbose_name="Copyright Link's Colour")),
                ('lnk_hov_footcopy', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the site copyright banner link on hover.', max_length=18, verbose_name="Copyright Link's Hover Colour")),
                ('bg_pagehead', colorfield.fields.ColorField(default='#f7f8fb', help_text='Applied to the default page header background.', max_length=18, verbose_name="Page Header Background's Colour")),
                ('txt_pagehead', colorfield.fields.ColorField(default='#202325', help_text='Applied to the default page header text.', max_length=18, verbose_name="Page Header Text's Colour")),
                ('lnk_pagehead', colorfield.fields.ColorField(default='#202325', help_text='Applied to the default page header link.', max_length=18, verbose_name="Page Header Link's Colour")),
                ('lnk_hov_pagehead', colorfield.fields.ColorField(default='#066bf9', help_text='Applied to the default page header link on hover.', max_length=18, verbose_name="Page Header Link's Hover Colour")),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'ordering': ['-pk'],
            },
        ),
    ]
