# Generated by Django 2.2.17 on 2020-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Theme')),
                ('css', models.TextField(blank=True, null=True, verbose_name='CSS')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
