# Generated by Django 2.2.17 on 2021-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmTheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememanagement',
            name='theme',
            field=models.CharField(help_text='Maximum 50 characters.', max_length=50, verbose_name='Theme'),
        ),
    ]
