# Generated by Django 2.2.18 on 2021-05-05 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmAdminTheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmadminlogs',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Admin Log', 'verbose_name_plural': 'Admin Logs'},
        ),
    ]
