# Generated by Django 2.2.17 on 2020-12-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0003_delete_stripeorderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeOrderData',
            fields=[
                ('order_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boutique.OrderPayment')),
                ('receipt_url', models.CharField(max_length=150, verbose_name='URL de réception')),
                ('stripe_session_data', models.TextField(verbose_name='Stripe données')),
                ('stripe_payment_data', models.TextField(verbose_name='Stripe de la facture')),
            ],
        ),
    ]
