# Generated by Django 2.2.17 on 2021-01-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmTaxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canadataxmanagement',
            options={'verbose_name': 'Canadian Tax', 'verbose_name_plural': 'Canadian Taxes'},
        ),
    ]
