# Generated by Django 2.2.17 on 2020-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de la méthode d'expédition")),
                ('identifier', models.CharField(choices=[('free-shipping', 'Envoi postal (gratuit)'), ('standard-shipping', 'Envoi postal (standard)'), ('express-shipping', 'Envoi postal (express)')], default='free-shipping', max_length=100, unique=True, verbose_name='Identifiant')),
                ('price', models.DecimalField(decimal_places=3, help_text='Un prix fixe ajouté au prix total du panier.', max_digits=30, verbose_name='Prix')),
            ],
            options={
                'verbose_name': "Méthode d'expédition",
                'verbose_name_plural': "Méthodes d'expédition",
            },
        ),
    ]
