# Generated by Django 2.2.17 on 2020-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='dshop.ProductCategory', verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, null=True, to='dshop.ProductFilter', verbose_name='Filtres'),
        ),
    ]
