# Generated by Django 2.2.17 on 2020-12-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0002_auto_20201215_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Is FeatureEemable?')),
            ],
        ),
    ]
