# Generated by Django 2.2.17 on 2021-01-05 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0005_auto_20210104_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurelist',
            options={'verbose_name': 'Feature List', 'verbose_name_plural': 'Feature Lists'},
        ),
        migrations.CreateModel(
            name='dmSiteLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logodark', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_dark', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo pour fond sombre')),
                ('logolight', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_light', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo pour fond clair')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='dshop.dmSite')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
