# Generated by Django 2.2.17 on 2021-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0007_auto_20210106_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
