# Generated by Django 2.2.17 on 2021-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0008_auto_20210106_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordered Quantity'),
            preserve_default=False,
        ),
    ]
