# Generated by Django 2.2.17 on 2021-01-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0009_delivery_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordered Quantity'),
            preserve_default=False,
        ),
    ]
