# Generated by Django 2.2.17 on 2021-01-07 17:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0010_auto_20210106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dminfolettre',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Subitle's Colour"),
        ),
        migrations.AddField(
            model_name='dminfolettre',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Text's Colour"),
        ),
        migrations.AddField(
            model_name='dminfolettre',
            name='title_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Title's Colour"),
        ),
    ]
