# Generated by Django 2.2.17 on 2021-01-07 16:26

from django.db import migrations, models
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0010_auto_20210106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefault',
            name='discounted_price',
            field=shop.money.fields.MoneyField(decimal_places=3, default=None, help_text='Net discounted price for this product.', verbose_name='Discounted Unit Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdefault',
            name='end_date',
            field=models.DateField(blank=True, help_text='Stop Date Discount', null=True, verbose_name='Discount Stop Date'),
        ),
        migrations.AddField(
            model_name='productdefault',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start Date Discount', null=True, verbose_name='Discount Start Date'),
        ),
        migrations.AddField(
            model_name='productvariablevariant',
            name='discounted_price',
            field=shop.money.fields.MoneyField(decimal_places=3, default=None, help_text='Net discounted price for this product.', verbose_name='Discounted Unit Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariablevariant',
            name='end_date',
            field=models.DateField(blank=True, help_text='Stop Date Discount', null=True, verbose_name='Discount Stop Date'),
        ),
        migrations.AddField(
            model_name='productvariablevariant',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start Date Discount', null=True, verbose_name='Discount Start Date'),
        ),
    ]
