# Generated by Django 2.2.17 on 2021-01-07 17:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0011_auto_20210107_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='dminfolettre',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour"),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Subtitle's Colour"),
        ),
    ]
