# Generated by Django 2.2.17 on 2021-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0011_auto_20210107_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefault',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Stop DateTime Discount', null=True, verbose_name='Discount Stop Date'),
        ),
        migrations.AlterField(
            model_name='productdefault',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start DateTime Discount', null=True, verbose_name='Discount Start DateTime'),
        ),
        migrations.AlterField(
            model_name='productvariablevariant',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Stop DateTime Discount', null=True, verbose_name='Discount Stop DateTime'),
        ),
        migrations.AlterField(
            model_name='productvariablevariant',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start DateTime Discount', null=True, verbose_name='Discount Start DateTime'),
        ),
    ]
