# Generated by Django 2.2.17 on 2021-01-07 17:46

import colorfield.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0012_auto_20210107_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmproductsbycategory',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour"),
        ),
        migrations.AddField(
            model_name='dmproductsbycategory',
            name='bg_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_image', to=settings.FILER_IMAGE_MODEL, verbose_name="Background's Image"),
        ),
    ]
