# Generated by Django 2.2.17 on 2021-01-07 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0013_auto_20210107_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Brand's Name")),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort by')),
                ('logo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'verbose_name': "Product's Brand",
                'verbose_name_plural': "Product's Brands",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dshop.ProductBrand', verbose_name='Brand'),
        ),
    ]
