# Generated by Django 2.2.17 on 2021-01-07 18:51

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dshop', '0014_auto_20210107_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmProductsBrands',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmproductsbrands', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('howmany', models.PositiveSmallIntegerField(default=5, help_text="How many brand's logo to be show at the same time.", verbose_name='Number')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
