# Generated by Django 2.2.17 on 2021-01-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0015_dmproductsbrands'),
        ('dshop', '0012_auto_20210107_1226'),
    ]

    operations = [
    ]
