# Generated by Django 2.2.17 on 2021-01-11 13:56

from django.db import migrations
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0017_auto_20210108_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdefault',
            name='discounted_price',
            field=shop.money.fields.MoneyField(blank=True, decimal_places=3, help_text='Net discounted price for this product.', null=True, verbose_name='Discounted Unit Price'),
        ),
        migrations.AlterField(
            model_name='productvariablevariant',
            name='discounted_price',
            field=shop.money.fields.MoneyField(blank=True, decimal_places=3, help_text='Net discounted price for this product.', null=True, verbose_name='Discounted Unit Price'),
        ),
    ]
