# Generated by Django 2.2.17 on 2021-01-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0021_dmbloctextmedia_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dshop.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='productvariablevariant',
            name='attribute',
            field=models.ManyToManyField(blank=True, to='dshop.AttributeValue', verbose_name='Attribute'),
        ),
    ]
