# Generated by Django 2.2.17 on 2021-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0022_auto_20210112_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='square_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Square ID'),
        ),
    ]
