# Generated by Django 2.2.17 on 2021-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0023_productcategory_square_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='Attribute Name', max_length=20, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='dshop.Attribute', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(help_text='Attribute Value', max_length=20, verbose_name='Attribute Value'),
        ),
    ]
