# Generated by Django 2.2.17 on 2021-01-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0025_auto_20210113_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': "Product's Attribute", 'verbose_name_plural': "Product's Attributes"},
        ),
        migrations.AddField(
            model_name='productvariable',
            name='square_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Square ID'),
        ),
    ]
