# Generated by Django 2.2.17 on 2021-01-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0026_auto_20210113_1240'),
        ('dshop', '0022_auto_20210112_1508'),
    ]

    operations = [
    ]
