# Generated by Django 2.2.17 on 2021-01-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0027_merge_20210113_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmTeamParent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmteamparent', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='dmTeamChild',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmteamchild', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Name')),
                ('job', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Job')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, help_text='Ex.: https://www.facebook.com/<username>', max_length=250, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, help_text='Ex.: https://twitter.com/<username>', max_length=250, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, help_text='Ex.: https://www.instagram.com/<username>', max_length=250, null=True, verbose_name='Instagram')),
                ('photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='team_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
