# Generated by Django 2.2.17 on 2021-01-14 15:33

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0028_dmteamchild_dmteamparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmteamchild',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
    ]
