# Generated by Django 2.2.17 on 2021-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0029_auto_20210114_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='Attribute Name', max_length=250, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(help_text='Attribute Value', max_length=250, verbose_name='Attribute Value'),
        ),
    ]
