# Generated by Django 2.2.17 on 2021-01-15 19:24

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0030_auto_20210114_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour"),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='An image that will be shown on the top of the page of the Products of this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to=settings.FILER_IMAGE_MODEL, verbose_name="Header's Image"),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='A text that will be shown on the top of the page of the Products of this category.', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Text's Colour"),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='text_position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Left'), (2, 'Center'), (3, 'Right')], default=1, help_text='Position of the text.', verbose_name='Position'),
        ),
    ]
