# Generated by Django 2.2.17 on 2021-01-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0032_auto_20210118_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'parent__name', 'name'], 'verbose_name': "Product's Category", 'verbose_name_plural': "Product's Categories"},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='mptt_level',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dshop.ProductCategory', verbose_name="Parent's Category"),
        ),
    ]
