# Generated by Django 2.2.17 on 2021-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0036_auto_20210119_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='text_position',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Left'), (1, 'Right')], default=1, verbose_name="Text's Position"),
        ),
        migrations.DeleteModel(
            name='CategoryTest',
        ),
    ]
