# Generated by Django 2.2.17 on 2021-01-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0037_auto_20210119_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'get_latest_by': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='deliveryitem',
            options={'get_latest_by': ['pk']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
