# Generated by Django 2.2.17 on 2021-01-26 19:36

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dshop', '0039_testimonialchild_testimonialparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmTestimonialChild',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmtestimonialchild', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(help_text='Maximum 1000 characters.', max_length=1000, verbose_name='Text')),
                ('text_color', colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name="Text's Colour")),
                ('name', models.CharField(blank=True, help_text='Maximum 250 characters.', max_length=250, null=True, verbose_name='Name')),
                ('name_color', colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name="Name's Colour")),
                ('bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour")),
                ('bg_image', models.ImageField(blank=True, help_text='Facultative. Size: 2000x900.', null=True, upload_to='', verbose_name="Background's Image")),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='dmTestimonialParent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmtestimonialparent', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='testimonialparent',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='TestimonialChild',
        ),
        migrations.DeleteModel(
            name='TestimonialParent',
        ),
    ]
