# Generated by Django 2.2.17 on 2021-01-26 19:44

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0040_auto_20210126_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmtestimonialchild',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
