# Generated by Django 2.2.17 on 2021-01-26 19:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0042_remove_dmtestimonialchild_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmtestimonialchild',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='dmtestimonialchild',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='dmtestimonialparent',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour"),
        ),
        migrations.AddField(
            model_name='dmtestimonialparent',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 2000x900.', null=True, upload_to='', verbose_name="Background's Image"),
        ),
    ]
