# Generated by Django 2.2.17 on 2021-01-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0043_auto_20210126_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtestimonialchild',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
