# Generated by Django 2.2.17 on 2021-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0044_dmtestimonialchild_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmbloctextmedia',
            name='text_align',
            field=models.BooleanField(default=True, verbose_name='Align text and media vertically?'),
        ),
    ]
