# Generated by Django 2.2.17 on 2021-01-27 15:24

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dshop', '0045_dmbloctextmedia_text_align'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmBlocText2Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmbloctext2column', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum 200 characters.', max_length=200, null=True, verbose_name='Subtitle')),
                ('text_left', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Left Text')),
                ('text_right', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Right Text')),
                ('text_align', models.BooleanField(default=False, verbose_name='Align texts vertically?')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
