# Generated by Django 2.2.17 on 2021-01-28 16:56

from django.db import migrations
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0047_auto_20210128_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariablevariant',
            name='discounted_price',
            field=shop.money.fields.MoneyField(blank=True, decimal_places=3, default=0, help_text='Net discounted price for this product.', null=True, verbose_name='Discounted Unit Price'),
        ),
    ]
