# Generated by Django 2.2.17 on 2021-02-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0050_auto_20210201_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': "Product's Category", 'verbose_name_plural': "Product's Categories"},
        ),
    ]
