# Generated by Django 2.2.17 on 2021-02-05 16:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0052_auto_20210205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlabel',
            name='bg_colour',
            field=colorfield.fields.ColorField(default='#fff', max_length=18, verbose_name="Background's Colour"),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Add a custom label to the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dshop.ProductLabel', verbose_name='Custom Label'),
        ),
        migrations.AlterField(
            model_name='productlabel',
            name='colour',
            field=colorfield.fields.ColorField(default='#000', max_length=18, verbose_name="Text's Colour"),
        ),
    ]
