# Generated by Django 2.2.18 on 2021-02-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0053_auto_20210205_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Filter's Group Name")),
            ],
        ),
        migrations.AddField(
            model_name='productfilter',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Add a group to Filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dshop.ProductFilterGroup', verbose_name='Filter Group'),
        ),
    ]
