# Generated by Django 2.2.17 on 2021-02-18 19:16

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('dshop', '0053_auto_20210205_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Document's name")),
                ('document', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Docunebt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_document', to='dshop.ProductVariable', verbose_name='Product')),
            ],
        ),
    ]
