# Generated by Django 2.2.18 on 2021-02-15 16:04

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0053_auto_20210205_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariablevariant',
            name='variant_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Variant Image'),
        ),
    ]
