# Generated by Django 2.2.18 on 2021-03-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0054_productdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='document',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Document's Name"),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_document', to='dshop.Product', verbose_name='Product'),
        ),
    ]
