# Generated by Django 2.2.18 on 2021-03-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0055_auto_20210302_1137'),
        ('dshop', '0054_productvariablevariant_variant_image'),
    ]

    operations = [
    ]
