# Generated by Django 2.2.18 on 2021-03-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0056_auto_20210224_1335'),
        ('dshop', '0056_merge_20210304_0938'),
    ]

    operations = [
    ]
