# Generated by Django 2.2.18 on 2021-03-09 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0057_merge_20210309_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
    ]
