# Generated by Django 2.2.18 on 2021-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0058_auto_20210309_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocksalesparent',
            name='perline',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 block'), (2, '2 blocks'), (3, '3 blocks')], default=2, verbose_name='How many block per line?'),
        ),
    ]
