# Generated by Django 2.2.18 on 2021-03-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0059_dmblocksalesparent_perline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmblocsliderchild',
            old_name='subtitle',
            new_name='suptitle',
        ),
        migrations.RenameField(
            model_name='dmblocsliderchild',
            old_name='subtitle_color',
            new_name='suptitle_color',
        ),
    ]
