# Generated by Django 2.2.18 on 2021-03-12 14:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0060_auto_20210312_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocsliderchild',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Maximum 200 characters.', max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='dmblocsliderchild',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Subtitle's Colour"),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='suptitle',
            field=models.CharField(blank=True, help_text='Maximum 200 characters.', max_length=200, null=True, verbose_name='Suptitle'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='suptitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Suptitle's Colour"),
        ),
    ]
