# Generated by Django 2.2.18 on 2021-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0062_dmsitecontact_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocsliderparent',
            name='height',
            field=models.PositiveSmallIntegerField(default=500, help_text='Height of the slider (will be automatically shrinked on mobile version).', verbose_name='Height'),
        ),
    ]
