# Generated by Django 2.2.18 on 2021-03-23 18:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0064_dmproductsbycategory_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='btn_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Leave blank to use transparent.', max_length=18, null=True, verbose_name="Button Background's Colour"),
        ),
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='btn_border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Leave blank to use transparent.', max_length=18, null=True, verbose_name="Button Border's Colour"),
        ),
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='btn_text_color',
            field=colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name="Button Text's Colour"),
        ),
    ]
