# Generated by Django 2.2.18 on 2021-03-24 16:06

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dshop', '0065_auto_20210323_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmBlocTextCarrousel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmbloctextcarrousel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum 200 characters.', max_length=200, null=True, verbose_name='Subtitle')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('text_align', models.BooleanField(default=True, verbose_name='Align text and media vertically?')),
                ('colposition', models.PositiveSmallIntegerField(choices=[(0, 'Left'), (1, 'Right')], default=1, verbose_name="Image's Position")),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='dmBlocTextCarrouselImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dshop_dmbloctextcarrouselimage', serialize=False, to='cms.CMSPlugin')),
                ('image', models.ImageField(help_text='Sizes : 398x531. Leave blank to hide image.', upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
