# Generated by Django 2.2.18 on 2021-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0066_dmbloctextcarrousel_dmbloctextcarrouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmbloctextcarrousel',
            name='see_dots',
            field=models.BooleanField(default=False, help_text='If checked, will display dots under carrousel for each image.', verbose_name='Show Dots?'),
        ),
        migrations.AddField(
            model_name='dmbloctextcarrousel',
            name='see_navs',
            field=models.BooleanField(default=True, help_text='If checked, will display navigation arrows both sides of the carrousel.', verbose_name='Show Navigation Arrows?'),
        ),
        migrations.AlterField(
            model_name='dmbloctextcarrouselimage',
            name='image',
            field=models.ImageField(help_text='Max sizes : 600x600. Always use the same ratio on the same carrousel.', upload_to='', verbose_name='Image'),
        ),
    ]
