# Generated by Django 2.2.18 on 2021-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0068_dmbloctextcarrousel_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmbloctextcarrousel',
            name='howmany_image',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many images to show at the same time on desktop.', verbose_name='How Many Images?'),
        ),
        migrations.AlterField(
            model_name='dmbloctextcarrousel',
            name='crop_image',
            field=models.BooleanField(default=False, help_text='If checked, will crop images to fit the same ratio.', verbose_name='Crop Image?'),
        ),
    ]
