# Generated by Django 2.2.18 on 2021-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0069_auto_20210324_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsitecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
