# Generated by Django 2.2.18 on 2021-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0070_auto_20210324_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsitecontact',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='dmsitecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
