# Generated by Django 2.2.18 on 2021-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0071_auto_20210329_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsite',
            name='google_analytics',
            field=models.TextField(blank=True, null=True, verbose_name='Google Analytics Snippet'),
        ),
    ]
