# Generated by Django 2.2.18 on 2021-04-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0072_auto_20210406_1012'),
        ('dshop', '0072_dmsite_google_analytics'),
    ]

    operations = [
    ]
