# Generated by Django 2.2.18 on 2021-04-07 16:38

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0074_auto_20210407_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsitelogo',
            name='favico_ico',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Size: 48x48. Format: .ico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favico_ico', to='filer.File', verbose_name='Favicon 48x48'),
        ),
    ]
