# Generated by Django 2.2.18 on 2021-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0075_auto_20210407_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfilter',
            options={'ordering': ['group', 'order', '-pk'], 'verbose_name': "Product's Filter", 'verbose_name_plural': "Product's Filters"},
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='description',
        ),
        migrations.AlterField(
            model_name='dmsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmsite', to='sites.Site'),
        ),
        migrations.CreateModel(
            name='ProductFilterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_trans', models.CharField(blank=True, max_length=100, null=True, verbose_name="Translated Filter's Name")),
                ('description', models.TextField(blank=True, null=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dshop.ProductFilter')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductFilterGroupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name_trans', models.CharField(blank=True, max_length=100, null=True, verbose_name="Translated Filter's Group Name")),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dshop.ProductFilterGroup')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
