# Generated by Django 2.2.18 on 2021-05-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0076_auto_20210409_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocument',
            options={'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
        migrations.AlterModelOptions(
            name='productvariablevariant',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='image',
        ),
    ]
