# Generated by Django 2.2.18 on 2021-05-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0077_auto_20210505_0103'),
        ('dshop', '0077_auto_20210504_1348'),
    ]

    operations = [
    ]
