# Generated by Django 2.2.18 on 2021-05-19 13:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('dshop', '0078_merge_20210505_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
    ]
