# Generated by Django 2.2.18 on 2021-05-31 16:54

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0083_auto_20210528_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmsitecontact',
            name='schedule',
        ),
        migrations.CreateModel(
            name='dmSiteContactTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='Schedule')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dshop.dmSiteContact')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
