# Generated by Django 2.2.18 on 2021-05-31 17:03

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0084_auto_20210531_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlabel',
            options={'ordering': ['-pk'], 'verbose_name': "Product's Label", 'verbose_name_plural': "Product's Labels"},
        ),
        migrations.RemoveField(
            model_name='productlabel',
            name='name',
        ),
        migrations.CreateModel(
            name='ProductLabelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='Maximum 25 characters.', max_length=25, verbose_name="Label's Name")),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dshop.ProductLabel')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
