# Generated by Django 2.2.18 on 2021-05-31 17:03

from django.db import migrations
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('dshop', 'AttributeValue')
    MyModelTranslation = apps.get_model('dshop', 'AttributeValueTranslation')

    for object in MyModel.objects.all():
        MyModelTranslation.objects.create(
            master_id=object.pk,
            language_code=settings.LANGUAGE_CODE,
            value_trans=object.value
        )

def backwards_func(apps, schema_editor):
    MyModel = apps.get_model('dshop', 'AttributeValue')
    MyModelTranslation = apps.get_model('dshop', 'AttributeValueTranslation')

    for object in MyModel.objects.all():
        translation = _get_translation(object, MyModelTranslation)
        object.value = translation.value_trans
        object.save()   # Note this only calls Model.save()

def _get_translation(object, MyModelTranslation):
    translations = MyModelTranslation.objects.filter(master_id=object.pk)
    try:
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
        except ObjectDoesNotExist:
            return translations.get()


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0085_attributevaluetranslation'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
