# Generated by Django 2.2.18 on 2021-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0086_auto_20210531_1703'),
        ('dshop', '0085_auto_20210531_1703'),
    ]

    operations = [
    ]
