# Generated by Django 2.2.18 on 2021-05-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0086_auto_20210531_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='product_name_trans',
            field=models.CharField(max_length=255, null=True, verbose_name="Product's Name"),
        ),
    ]
