# Generated by Django 2.2.18 on 2021-05-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0088_auto_20210531_1736'),
        ('dshop', '0087_merge_20210531_1717'),
    ]

    operations = [
    ]
