# Generated by Django 2.2.18 on 2021-05-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0089_merge_20210531_1802'),
        ('dshop', '0089_merge_20210531_1810'),
    ]

    operations = [
    ]
