# Generated by Django 2.2.18 on 2021-06-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0090_merge_20210531_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmblocsliderparent',
            name='height',
            field=models.PositiveSmallIntegerField(default=500, help_text='Height of the slider            (will be automatically shrinked on mobile version).', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='dmbloctextcarrousel',
            name='see_navs',
            field=models.BooleanField(default=True, help_text='If checked, will display navigation             arrows both sides of the carrousel.', verbose_name='Show Navigation Arrows?'),
        ),
        migrations.AlterField(
            model_name='dmbloctextcarrouselimage',
            name='image',
            field=models.ImageField(help_text='Max sizes : 600x600. Always             use the same ratio on the same carrousel.', upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='An image that will be shown on the top of             the page of the Products of this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to=settings.FILER_IMAGE_MODEL, verbose_name="Header's Image"),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='A text that will be shown on the top of             the page of the Products of this category.', null=True, verbose_name='Text'),
        ),
    ]
