# Generated by Django 2.2.18 on 2021-08-04 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0091_auto_20210614_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmblocetapeschild',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 160x160.', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblocetapeschild',
            name='text',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dmblocetapeschild',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmblocetapesparent',
            name='subtitle',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dmblocetapesparent',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='btn_label',
            field=models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name="Button's Label"),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 420x460.', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='text',
            field=models.CharField(blank=True, help_text='Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='btn_label',
            field=models.CharField(blank=True, help_text='Maximum 100 characters.', max_length=100, null=True, verbose_name="Button's Label"),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 540x300.', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='text',
            field=models.CharField(blank=True, help_text='Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmblocksalesparent',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 2000x900. Leave blank to hide image.', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='label',
            field=models.CharField(default='Subscribe to our newsletter', help_text='Maximum 255 characters.', max_length=255, verbose_name="Button's Label"),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Facultative. Maximum 1000 characters.', max_length=1000, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Facultative.', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='title',
            field=models.CharField(blank=True, help_text='Facultative. Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='facebook',
            field=models.URLField(blank=True, help_text='Ex.: https://www.facebook.com/<username>', max_length=1000, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ex.: https://www.instagram.com/<username>', max_length=1000, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='name',
            field=models.CharField(help_text='Maximum 255 characters.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 255x355.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='dmteamchild',
            name='twitter',
            field=models.URLField(blank=True, help_text='Ex.: https://twitter.com/<username>', max_length=1000, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='dmteamparent',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dmtestimonialchild',
            name='name',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dmtestimonialchild',
            name='photo',
            field=models.ImageField(blank=True, help_text='Facultative. Size: 120x120.', null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='dmtestimonialparent',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
