# Generated by Django 2.2.18 on 2021-08-04 15:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0092_auto_20210804_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmbloccontact',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Background's Colour"),
        ),
        migrations.AddField(
            model_name='dmbloccontact',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Text's Colour"),
        ),
    ]
