# Generated by Django 2.2.18 on 2021-08-19 15:49

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0094_auto_20210819_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmblocetapeschild',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 160x160.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_etapeschild_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 420x460.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_calltoaction_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 540x300.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_saleschild_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Maximum size: 1920x900. Leave blank to hide image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_sliderchild_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmbloctextmedia',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Sizes : 398x531. Leave blank to hide image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_textmedia_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmbloctextmedia',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Leave blank to hide or use image instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_textmedia_video', to='filer.File', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='dminfolettre',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 2000x900. Leave blank to hide image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_infolettre_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmtestimonialchild',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 120x120.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_testimonialchild_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='dmtestimonialparent',
            name='bg_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Facultative. Size: 2000x900.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmplugin_testimonialparent_bgimage', to=settings.FILER_IMAGE_MODEL, verbose_name="Background's Image"),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Size: 300x300.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo'),
        ),
    ]
