# Generated by Django 2.2.18 on 2021-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0095_auto_20210819_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfiltergroup',
            options={'ordering': ['order', '-pk'], 'verbose_name': "Product's Filter Group", 'verbose_name_plural': "Product's Filter Groups"},
        ),
        migrations.RenameField(
            model_name='productfiltertranslation',
            old_name='name_trans',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcategorytranslation',
            name='name_trans',
        ),
        migrations.RemoveField(
            model_name='productfilter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productfiltergroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productfiltergrouptranslation',
            name='name_trans',
        ),
        migrations.AddField(
            model_name='productcategorytranslation',
            name='name',
            field=models.CharField(default='temporaire', help_text='Maximum 255 characters.', max_length=255, verbose_name='Category Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfiltergrouptranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name="Filter's Group Name"),
        ),
    ]
