# Generated by Django 2.2.18 on 2021-08-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dshop', '0096_auto_20210825_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfiltertranslation',
            name='name',
            field=models.CharField(blank=True, help_text='Maximum 255 characters.', max_length=255, null=True, verbose_name="Filter's Name"),
        ),
    ]
