# Generated by Django 2.2.17 on 2020-11-27 14:52

from django.db import migrations, models
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdefault',
            options={'verbose_name': 'Produit par défaut', 'verbose_name_plural': 'Produits par défaut'},
        ),
        migrations.AlterModelOptions(
            name='productdefaulttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Produit par défaut Translation'},
        ),
        migrations.AddField(
            model_name='productdefault',
            name='product_code',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Product code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdefault',
            name='unit_price',
            field=shop.money.fields.MoneyField(decimal_places=3, default=1, help_text='Net price for this product', verbose_name='Unit price'),
            preserve_default=False,
        ),
    ]
