# Generated by Django 2.2.17 on 2020-12-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingManagement',
        ),
    ]
