# Generated by Django 2.2.17 on 2020-11-27 14:54

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20201127_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='caption',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Description longue.', null=True, verbose_name='Description'),
        ),
    ]
