# Generated by Django 2.2.17 on 2020-12-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_delete_shippingmanagement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeOrderData',
        ),
    ]
