# Generated by Django 2.2.17 on 2020-11-27 14:55

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_auto_20201127_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Description longue.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='caption',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Description courte.', null=True, verbose_name='Caption'),
        ),
    ]
