# Generated by Django 2.2.17 on 2020-12-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_delete_stripeorderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dmRabaisPerCategory',
        ),
    ]
