# Generated by Django 2.2.17 on 2020-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_auto_20201127_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vedette',
            field=models.BooleanField(default=False, verbose_name='En vedette ?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='productdefault',
            name='product_code',
            field=models.CharField(help_text='Un code unique.', max_length=255, unique=True, verbose_name='Code du produit'),
        ),
    ]
