# Generated by Django 2.2.17 on 2020-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_auto_20201127_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='boutique.ProductCategory', verbose_name='Catégories'),
        ),
    ]
