# Generated by Django 2.2.17 on 2020-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_auto_20201201_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(to='boutique.ProductFilter', verbose_name='Filtres'),
        ),
    ]
