# Generated by Django 2.2.17 on 2020-12-02 20:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadataxmanagement',
            name='state',
            field=models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New-Brunswick', 'New-Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Northwest Territories', 'Northwest Territories'), ('Nova Scotia', 'Nova Scotia'), ('Nunavut', 'Nunavut'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Yukon', 'Yukon')], max_length=60, unique=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Couleur de fond'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='subtitle_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Couleur du sous-titre'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='title_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Couleur du titre'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='title_shadow',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name="Couleur d'ombre du titre"),
        ),
    ]
