# Generated by Django 2.2.17 on 2020-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_auto_20201202_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocsliderchild',
            name='btn_blank',
            field=models.BooleanField(default=False, verbose_name="Le bouton s'ouvre dans un nouvel onglet ?"),
        ),
        migrations.AddField(
            model_name='dmblocsliderchild',
            name='btn_label',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom du bouton'),
        ),
        migrations.AddField(
            model_name='dmblocsliderchild',
            name='btn_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lien URL du bouton'),
        ),
    ]
