# Generated by Django 2.2.17 on 2020-12-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_auto_20201202_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='btn_blank',
            field=models.BooleanField(default=False, verbose_name="Le lien s'ouvre dans un nouvel onglet ?"),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='btn_label',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom du lien'),
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='btn_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adresse URL du lien'),
        ),
    ]
