# Generated by Django 2.2.17 on 2020-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_auto_20201202_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='dmblocsliderchild',
            name='title_shadow',
        ),
        migrations.AlterField(
            model_name='dmblocsliderchild',
            name='image',
            field=models.ImageField(blank=True, help_text="Laisser vide pour ne pas afficher d'image.", null=True, upload_to='', verbose_name='Image'),
        ),
    ]
