# Generated by Django 2.2.17 on 2020-12-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_auto_20201203_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ordered Item', 'verbose_name_plural': 'Ordered Items'},
        ),
    ]
