# Generated by Django 2.2.17 on 2020-12-03 15:53

from django.db import migrations
import shop.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_auto_20201203_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variables',
            field=shop.models.fields.JSONField(verbose_name='Données'),
        ),
    ]
