# Generated by Django 2.2.17 on 2020-12-07 12:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0016_auto_20201203_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#f7f8fb', max_length=18, verbose_name='Couleur de fond'),
        ),
        migrations.AddField(
            model_name='dmblocksaleschild',
            name='txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Couleur du texte'),
        ),
    ]
