# Generated by Django 2.2.17 on 2020-12-07 12:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0017_auto_20201207_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#f2f2f3', max_length=18, verbose_name='Couleur de fond'),
        ),
        migrations.AlterField(
            model_name='dmblocksaleschild',
            name='txt_color',
            field=colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name='Couleur du texte'),
        ),
    ]
