# Generated by Django 2.2.17 on 2020-12-07 12:48

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('boutique', '0018_auto_20201207_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmBlockCalltoaction',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='boutique_dmblockcalltoaction', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte')),
                ('txt_color', colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name='Couleur du texte')),
                ('btn_label', models.CharField(blank=True, max_length=25, null=True, verbose_name="Button's Label")),
                ('btn_url', models.CharField(blank=True, max_length=255, null=True, verbose_name="Button's URL")),
                ('bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Couleur de fond')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
