# Generated by Django 2.2.17 on 2020-12-07 12:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0019_dmblockcalltoaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmblockcalltoaction',
            old_name='txt_color',
            new_name='text_color',
        ),
        migrations.AddField(
            model_name='dmblockcalltoaction',
            name='subtitle_color',
            field=colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name='Couleur du sous-titre'),
        ),
        migrations.AddField(
            model_name='dmblockcalltoaction',
            name='title_color',
            field=colorfield.fields.ColorField(default='#292b2c', max_length=18, verbose_name='Couleur du titre'),
        ),
        migrations.AlterField(
            model_name='dmblockcalltoaction',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-titre'),
        ),
    ]
