# Generated by Django 2.2.17 on 2020-12-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('boutique', '0020_auto_20201207_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmSiteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Youtube')], default=1, verbose_name='Réseau social')),
                ('url', models.CharField(max_length=1000, verbose_name='Lien vers le réseau')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
            },
        ),
    ]
