# Generated by Django 2.2.17 on 2020-12-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('boutique', '0021_dmsitesocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='dmsitesocial',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.dmSite'),
        ),
    ]
