# Generated by Django 2.2.17 on 2020-12-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0022_auto_20201207_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmsite',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Site'},
        ),
        migrations.AlterField(
            model_name='dmsitesocial',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='boutique.dmSite'),
        ),
    ]
