# Generated by Django 2.2.17 on 2020-12-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0023_auto_20201207_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='dmSiteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Courriel')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adresse')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='boutique.dmSite')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
