# Generated by Django 2.2.17 on 2020-12-08 15:13

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0024_dmsitecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image principale'),
        ),
    ]
