# Generated by Django 2.2.18 on 2021-03-24 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('dmPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmportfolio',
            options={'verbose_name': "Portfolio's Item", 'verbose_name_plural': "Portfolio's Items"},
        ),
        migrations.AlterField(
            model_name='dmportfolio',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dmportfolio',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dmportfolio',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250, verbose_name='Title'),
        ),
    ]
