# Generated by Django 2.2.17 on 2021-02-08 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmStockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Product Name')),
                ('product_square_code', models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Product Square Code')),
                ('variant_square_code', models.CharField(help_text='Maximum 100 characters.', max_length=100, verbose_name='Variant Square Code')),
                ('old_quantity', models.PositiveIntegerField(default=0, help_text='Old quantity in stock.', verbose_name='Old Quantity')),
                ('new_quantity', models.PositiveIntegerField(default=0, help_text='New quantity in stock.', verbose_name='New Quantity')),
                ('stock_update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Stock Adjustment')),
                ('update_from', models.PositiveSmallIntegerField(choices=[(1, 'Dshop to Square'), (2, 'Square to Dshop')], default=2, verbose_name='Stock Updated From')),
            ],
            options={
                'verbose_name': 'Stock Log',
                'verbose_name_plural': 'Stocks Log',
            },
        ),
    ]
