# Generated by Django 2.2.17 on 2021-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmSquare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmstocklog',
            name='new_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='New Quantity'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Old Quantity'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='product_square_code',
            field=models.CharField(max_length=100, verbose_name='Product Square Code'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='variant_square_code',
            field=models.CharField(max_length=100, verbose_name='Variant Square Code'),
        ),
    ]
