# Generated by Django 2.2.18 on 2021-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmSquare', '0003_auto_20210209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmstocklog',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='product_square_code',
            field=models.CharField(max_length=255, verbose_name='Product Square Code'),
        ),
        migrations.AlterField(
            model_name='dmstocklog',
            name='variant_square_code',
            field=models.CharField(max_length=255, verbose_name='Variant Square Code'),
        ),
    ]
